export const SELECT_GENDER = "SELECT_GENDER";
export const SELECT_RACE = "SELECT_RACE";
export const SELECT_CLASS = "SELECT_CLASS";
export const INCREASE_ATTRIBUTE = "INCREASE_ATTRIBUTE";
export const DECREASE_ATTRIBUTE = "DECREASE_ATTRIBUTE";
